### ISSUE TITLE
Adding a new Task Under Elements (Milestones)

### ISSUE THREAD

**Issue by wiamnasr** [PeterAhern/CYF-FP-development-planner#10]
## Story

**As a** Graduate

**I Want** to be able to add a new task/insight under a chosen element/milestone (Technical, Communication or Employability)

**So That** I can keep track of what I am working on / will work on and submit evidence of my work for feedback from a mentor

## Acceptance Criteria

1. I should be able to add a new task, with a title
2. I also optionally can add deadline, status(progress) and a link to my work (google drive link for example)
3. I should be able to edit any task's content
4. Upon clicking on a created task under elements(milestones) the task opens in an overlay as a modal
5. Task can be deleted!
6. Task can be closed by either clicking outside modal or by clicking close button

## Implementation Notes

1. Create a Task Component that accepts as props all the required fields (title, deadline,...)
2. The Task component should be rendered (possibly react Portal to render it under the root component with document.getElementById("ID_OF_DOM_TAG")) as an overlay modal
3. The task will be form data in itself, it will collect user information and will display it back to them
4. When clicking the edit button, the form data state is updated and reflected, without redirecting user from current opened task, until they choose to close the modal
5. Delete task button deletes the task from the list of rendered tasks under a certain Element(Milestone)

## Checklist:

- [x] I have created a form for user data collection for the task
- [x] I have connected this form into the Elements 's "add Task" button that will open in an overlay form editor when clicked (empty)
- [x] I have included the required fields in the form; Task title (cannot be empty), Task deadline, progress, link, delete button and close button
- [x] When I click outside the overlay, it doesn't close, until I click the close/delete button
- [x] When I click when in edit mode, the edit button is replaced with update button, which will update any changed information in the fields when clicked
- [ ] I can pick the deadline from a calculator, for now the time will be set as the midnight of the date chosen (End of Day - EOD)
